### ISSUE TITLE
websocket close?

### ISSUE THREAD

**Issue by cyberfly79** [thomasloven/lovelace-player#3]
Hi,

I use this player, it works very well. But after x minutes (idle time), the websocket is closes.
How do I fix it? At this time, the wifi connection is live.
This is  a wallpanel (Samsung SM-T580) (chrome)

Thanks!

Cyber

**Comment by thomasloven** [comment]
Try my just released custom component [browser_mod](https://github.com/thomasloven/hass-browser_mod).
It handles websockets better and should be much more stable overall.
