### ISSUE TITLE
fully loses token - able to use the fully token instead of random one?

### ISSUE THREAD

**Issue by jschwalbe** [thomasloven/lovelace-player#5]
I've noticed that if I do a reset (Clear Cache) of fully, then there is a new ID (at least I think that's what happened). Since fully has it's own device ID which presumably doesn't ever change, would there be a way to use that device ID w/ the player?

**Comment by thomasloven** [comment]
That's odd. It *should* be using the fully deviceID if available. I'll look into it if I manage to kick my cheap-ass android tablet back to life...

**Comment by jschwalbe** [comment]
just curious, if you're not using fully on a crappy android, what do you use instead? (I'm unhappy with my tablet but can't figure out how to make an iPad turn on when I want it to w/o the lock screen needing to be swiped)

**Comment by thomasloven** [comment]
I *am* normally. It just crashed the other day and refuses to boot. But that's happened before, so I should be able to get it up again when I have the time.

**Comment by jschwalbe** [comment]
ugh mine did, too. just yesterday. held power button for about a minute and it started back up but it's slow and clunky even though literally all it's doing is displaying a website. (ok it's also listening for sound to wake up)

**Comment by thomasloven** [comment]
Let that be a lesson to us that you get what you pay for...

**Comment by thomasloven** [comment]
You need to enable JavaScript Interface under Advanced Web Settings.
